name: Auto merge PR
on:
  pull_request:
    types: [labeled]
    branches:
      - development
jobs:
  Run Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          auto-delete: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
