name: verify-pr

on: pull_request
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/test.sh
