name: publish-after-push-master

on:
  push:
    branches:
      - master

env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/test.sh
      - run: bash ./scripts/publish.sh
