name: publish-after-push-master

on:
  push:
    branches:
      - master

env:
  CI: true
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          fetch-depth: '0'
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/test.sh
      - run: bash ./scripts/publish.sh
